# Generated by Django 2.2 on 2021-07-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('order', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=255)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tile')),
            ],
        ),
    ]
